/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion } from 'motion/react';
import { 
  Sparkles, CheckCircle2, AlertCircle, Target, FileText, 
  Award, Copy, Plus, Clipboard, ChevronRight, BarChart3,
  TrendingUp, ShieldCheck, Zap, BookOpen, RefreshCw
} from 'lucide-react';
import { 
  ResponsiveContainer, RadarChart, PolarGrid, 
  PolarAngleAxis, PolarRadiusAxis, Radar 
} from 'recharts';
import { Button } from '../../ui/Button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../ui/Card';
import { Badge } from '../../ui/Badge';
import { useResume } from '../../../hooks/useResume';
import { useCareer } from '../../../contexts/CareerContext';
import { useAuth } from '../../../contexts/AuthContext';
import { cn } from '../../../lib/utils';

export const AtsAnalyzer: React.FC = () => {
  const { user } = useAuth();
  const { activeResume, latestAnalysis, runAtsAnalysis, isAnalyzing } = useResume();
  const { addNotification } = useCareer();

  // Inputs
  const [resumeText, setResumeText] = useState<string>(() => {
    if (activeResume) {
      const p = activeResume.content.personalInfo;
      const summary = activeResume.content.summary;
      const exps = activeResume.content.experience.map(e => `${e.title} at ${e.subtitle}\n${e.bullets?.join('\n')}`).join('\n\n');
      const projs = activeResume.content.projects.map(pr => `${pr.title}: ${pr.bullets?.join('\n')}`).join('\n\n');
      const sk = activeResume.content.skills.map(s => `${s.category}: ${s.items.join(', ')}`).join('\n');
      return `${p.fullName} | ${p.email} | ${p.phone} | ${p.headline}\n\nSUMMARY:\n${summary}\n\nEXPERIENCE:\n${exps}\n\nPROJECTS:\n${projs}\n\nSKILLS:\n${sk}`;
    }
    return '';
  });

  const [jobDescription, setJobDescription] = useState<string>('');
  const [generatedBullets, setGeneratedBullets] = useState<string[]>([]);
  const [isGeneratingBullets, setIsGeneratingBullets] = useState<boolean>(false);

  const handleAnalyze = async () => {
    if (!resumeText.trim()) {
      addNotification('Resume Content Required', 'Please paste or populate your resume text before analyzing.', 'warning');
      return;
    }

    const result = await runAtsAnalysis(resumeText, jobDescription, user?.currentTargetGoal);
    if (result) {
      addNotification('ATS Analysis Saved', `Score: ${result.readinessScore}% - Saved to Supabase database.`, 'success');
    } else {
      addNotification('Analysis Error', 'Failed to generate ATS parsing nodes.', 'warning');
    }
  };

  const handleGenerateBullets = async () => {
    if (!latestAnalysis || !latestAnalysis.keywordsMissing || latestAnalysis.keywordsMissing.length === 0) return;
    setIsGeneratingBullets(true);
    try {
      const promptText = `Generate 3 high-impact STAR resume bullet points targeting a "${user?.currentTargetGoal || 'Software Engineer'}" role incorporating missing keywords: ${latestAnalysis.keywordsMissing.slice(0, 4).join(', ')}. Include realistic metrics.`;
      
      const response = await fetch('/api/resume/improve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text: promptText,
          type: 'experience',
          targetRole: user?.currentTargetGoal
        })
      });
      const data = await response.json();
      if (data.text) {
        const bullets = data.text.split('\n').filter((l: string) => l.trim().length > 10).map((l: string) => l.replace(/^[-*•\s\d.]+/g, '').trim());
        setGeneratedBullets(bullets.length > 0 ? bullets : [data.text]);
        addNotification('STAR Bullets Generated', 'Tailored accomplishment bullets generated by Gemini AI.', 'success');
      }
    } catch {
      addNotification('AI Error', 'Could not compile tailored accomplishment bullets.', 'warning');
    } finally {
      setIsGeneratingBullets(false);
    }
  };

  const handleCopyBullet = (text: string) => {
    navigator.clipboard.writeText(text);
    addNotification('Copied', 'STAR bullet copied to clipboard.', 'success');
  };

  // Recharts radar data preparation
  const radarData = latestAnalysis ? [
    { subject: 'Languages', A: (latestAnalysis.skillRadarScores?.languages || 5) * 10 },
    { subject: 'Frameworks', A: (latestAnalysis.skillRadarScores?.frameworks || 5) * 10 },
    { subject: 'Architecture', A: (latestAnalysis.skillRadarScores?.architecture || 5) * 10 },
    { subject: 'Soft Skills', A: (latestAnalysis.skillRadarScores?.softSkills || 5) * 10 },
    { subject: 'Testing', A: (latestAnalysis.skillRadarScores?.testing || 5) * 10 },
    { subject: 'Tooling', A: (latestAnalysis.skillRadarScores?.tooling || 5) * 10 },
  ] : [
    { subject: 'Languages', A: 70 },
    { subject: 'Frameworks', A: 60 },
    { subject: 'Architecture', A: 80 },
    { subject: 'Soft Skills', A: 85 },
    { subject: 'Testing', A: 50 },
    { subject: 'Tooling', A: 75 },
  ];

  const score = latestAnalysis?.readinessScore || 78;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 w-full items-start animate-fade-in">
      
      {/* Inputs Column (5 cols) */}
      <div className="lg:col-span-5 flex flex-col gap-4">
        
        {/* Paste Resume Box */}
        <Card className="bg-[var(--surface)] border-[var(--border)] p-5">
          <CardHeader className="p-0 pb-3 border-b border-[var(--border)]/60">
            <CardTitle className="text-sm font-black text-text-main flex items-center gap-1.5">
              <FileText className="w-4 h-4 text-primary" /> Resume Ingest Sandbox
            </CardTitle>
            <CardDescription className="text-xs">
              Paste or verify the plain text of your resume to evaluate keyword match.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-0 pt-3 flex flex-col gap-3">
            <textarea
              rows={9}
              value={resumeText}
              onChange={e => setResumeText(e.target.value)}
              className="w-full text-xs p-3 font-mono border border-[var(--border)] rounded-lg bg-[var(--surface-secondary)]/50 focus:border-primary focus:outline-none transition-colors scrollbar-thin"
              placeholder="Paste plain text of your resume here..."
            />
          </CardContent>
        </Card>

        {/* Target JD Box */}
        <Card className="bg-[var(--surface)] border-[var(--border)] p-5">
          <CardHeader className="p-0 pb-3 border-b border-[var(--border)]/60">
            <CardTitle className="text-sm font-black text-text-main flex items-center gap-1.5">
              <Target className="w-4 h-4 text-primary" /> Target Job Posting (Optional)
            </CardTitle>
            <CardDescription className="text-xs">
              Paste a specific job description to calculate exact match index.
            </CardDescription>
          </CardHeader>

          <CardContent className="p-0 pt-3 flex flex-col gap-3">
            <textarea
              rows={4}
              value={jobDescription}
              onChange={e => setJobDescription(e.target.value)}
              className="w-full text-xs p-3 border border-[var(--border)] rounded-lg bg-[var(--surface-secondary)]/50 focus:border-primary focus:outline-none transition-colors scrollbar-thin"
              placeholder="Paste job description requirements..."
            />

            <Button
              variant="primary"
              size="sm"
              onClick={handleAnalyze}
              disabled={isAnalyzing || !resumeText.trim()}
              className="text-xs font-black h-9 flex items-center justify-center gap-2 mt-1 cursor-pointer"
            >
              {isAnalyzing ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" /> Analyzing with Gemini AI...
                </>
              ) : (
                <>
                  <Sparkles className="w-3.5 h-3.5 text-black" /> Run Gemini ATS Audit
                </>
              )}
            </Button>
          </CardContent>
        </Card>

      </div>

      {/* Analysis Results Column (7 cols) */}
      <div className="lg:col-span-7 flex flex-col gap-5">
        
        {/* Score Overview & Radar */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Gauge score card */}
          <Card className="bg-[var(--surface)] border-[var(--border)] p-5 flex flex-col justify-between">
            <div>
              <span className="text-[10px] font-bold text-text-mute uppercase tracking-wider">Overall ATS Readiness</span>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="text-4xl font-black text-primary">{score}%</span>
                <span className="text-xs text-text-sub font-semibold">
                  {score >= 80 ? 'Excellent Match' : score >= 60 ? 'Moderate Alignment' : 'Needs Optimizing'}
                </span>
              </div>
              <p className="text-xs text-text-sub leading-relaxed mt-2">
                Evaluated against recruitment parser algorithms, contact positioning, and technical keyterm density.
              </p>
            </div>

            <div className="w-full bg-[var(--surface-secondary)] rounded-full h-2.5 overflow-hidden my-3">
              <div className="bg-primary h-full transition-all duration-500" style={{ width: `${score}%` }} />
            </div>

            <div className="text-[10px] text-text-mute font-medium">
              Persisted in Supabase database
            </div>
          </Card>

          {/* Skill Radar Chart */}
          <Card className="bg-[var(--surface)] border-[var(--border)] p-3 flex flex-col items-center justify-center">
            <span className="text-[10px] font-bold text-text-mute uppercase tracking-wider self-start mb-1">Competency Radar</span>
            <div className="w-full h-44">
              <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                  <PolarGrid stroke="var(--border)" />
                  <PolarAngleAxis dataKey="subject" tick={{ fill: 'var(--text-sub)', fontSize: 9 }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} />
                  <Radar name="Skills" dataKey="A" stroke="#10b981" fill="#10b981" fillOpacity={0.4} />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </Card>

        </div>

        {/* Keywords Found vs Missing */}
        <Card className="bg-[var(--surface)] border-[var(--border)] p-5">
          <CardHeader className="p-0 pb-3 border-b border-[var(--border)]/60">
            <CardTitle className="text-sm font-black text-text-main flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-primary" /> Keyword Alignment Analysis
            </CardTitle>
          </CardHeader>

          <CardContent className="p-0 pt-4 flex flex-col gap-4">
            
            {/* Keywords Found */}
            <div>
              <span className="text-xs font-bold text-emerald-500 flex items-center gap-1.5 mb-2">
                <CheckCircle2 className="w-3.5 h-3.5" /> Keywords Identified ({latestAnalysis?.keywordsFound?.length || 0})
              </span>
              <div className="flex flex-wrap gap-1.5">
                {(latestAnalysis?.keywordsFound || ['TypeScript', 'React', 'Node.js', 'Express', 'SQL', 'Git', 'REST APIs']).map((kw, i) => (
                  <Badge key={i} variant="primary" className="text-[10px] font-bold bg-emerald-500/10 text-emerald-500 border-emerald-500/30">
                    {kw}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Keywords Missing */}
            <div>
              <span className="text-xs font-bold text-amber-500 flex items-center gap-1.5 mb-2">
                <AlertCircle className="w-3.5 h-3.5" /> Missing / Recommended Keyterms ({latestAnalysis?.keywordsMissing?.length || 0})
              </span>
              <div className="flex flex-wrap gap-1.5">
                {(latestAnalysis?.keywordsMissing || ['Docker', 'Google Cloud Run', 'CI/CD', 'Redis', 'Unit Testing']).map((kw, i) => (
                  <Badge key={i} variant="neutral" className="text-[10px] font-bold text-amber-500 border-amber-500/40 bg-amber-500/5">
                    + {kw}
                  </Badge>
                ))}
              </div>
            </div>

          </CardContent>
        </Card>

        {/* Structural Improvements Advice */}
        <Card className="bg-[var(--surface)] border-[var(--border)] p-5">
          <CardHeader className="p-0 pb-3 border-b border-[var(--border)]/60">
            <CardTitle className="text-sm font-black text-text-main flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-primary" /> Actionable Structural Improvements
            </CardTitle>
          </CardHeader>

          <CardContent className="p-0 pt-3">
            <ul className="flex flex-col gap-2.5 text-xs text-text-sub">
              {(latestAnalysis?.structuralImprovements || [
                'Incorporate quantitative metrics (e.g., % latency reduction, % revenue uplift) into bullet points.',
                'Ensure primary contact details, GitHub handle, and LinkedIn URL are in the top header.',
                'Maintain consistent bullet formatting and line spacing across all section items.'
              ]).map((item, idx) => (
                <li key={idx} className="flex items-start gap-2 bg-[var(--surface-secondary)]/50 p-2.5 rounded-md border border-[var(--border)]/50">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5 shrink-0" />
                  <span className="leading-relaxed">{item}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* STAR Accomplishment Generator */}
        <Card className="bg-[var(--surface)] border-[var(--border)] p-5">
          <CardHeader className="p-0 pb-3 border-b border-[var(--border)]/60 flex flex-row items-center justify-between">
            <CardTitle className="text-sm font-black text-text-main flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-500" /> AI STAR Bullet Statement Generator
            </CardTitle>
            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerateBullets}
              disabled={isGeneratingBullets}
              className="text-xs font-bold h-7"
            >
              {isGeneratingBullets ? 'Generating...' : 'Generate STAR Statements'}
            </Button>
          </CardHeader>

          <CardContent className="p-0 pt-3">
            {generatedBullets.length === 0 ? (
              <p className="text-xs text-text-sub italic">
                Click above to generate tailored STAR methodology bullet points incorporating missing technical keyterms.
              </p>
            ) : (
              <div className="flex flex-col gap-2.5">
                {generatedBullets.map((bullet, idx) => (
                  <div key={idx} className="bg-[var(--surface-secondary)] p-3 rounded-md border border-[var(--border)] flex items-start justify-between gap-3">
                    <p className="text-xs text-text-main leading-relaxed font-mono">{bullet}</p>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopyBullet(bullet)}
                      className="h-7 px-2 shrink-0 text-xs font-bold text-primary"
                    >
                      <Copy className="w-3.5 h-3.5 mr-1" /> Copy
                    </Button>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

      </div>

    </div>
  );
};
