/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { motion } from 'motion/react';
import { 
  Briefcase, Play, TrendingUp, Target, Lightbulb, ArrowRight
} from 'lucide-react';
import { Button } from '../../ui/Button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../../ui/Card';
import { Badge } from '../../ui/Badge';
import { CompanyName, QuestionCategory } from './InterviewTypes';

interface CaseStudyInterviewViewProps {
  onStartConfig: (prefill?: { type: any; company: any; difficulty: any; category: any }) => void;
}

export const CaseStudyInterviewView: React.FC<CaseStudyInterviewViewProps> = ({ onStartConfig }) => {
  const caseScenarios = [
    {
      title: 'Product Feature Prioritization & Execution',
      desc: 'How would you evaluate whether to build Google Maps Offline Navigation vs Real-Time Transit Crowding for emerging markets?',
      company: 'Google' as CompanyName,
      category: 'Product Management' as QuestionCategory
    },
    {
      title: 'Market Sizing & Fermi Estimation',
      desc: 'Estimate the total annual cloud infrastructure storage demand generated by autonomous vehicle telemetry in North America.',
      company: 'Tesla' as CompanyName,
      category: 'Problem Solving' as QuestionCategory
    },
    {
      title: 'Root Cause Metrics Diagnostic',
      desc: 'Meta Reels daily active watch time dropped by 14% week-over-week in Western Europe. How do you isolate the root cause?',
      company: 'Meta' as CompanyName,
      category: 'Projects' as QuestionCategory
    }
  ];

  return (
    <div className="flex flex-col gap-6 w-full animate-fade-in">
      
      {/* Banner */}
      <div className="p-6 rounded-card border border-[var(--border)] bg-[var(--surface)] shadow-md flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex flex-col max-w-2xl">
          <Badge variant="primary" className="text-[9px] uppercase tracking-widest font-black px-2.5 py-0.5 self-start mb-3 bg-primary/10 text-primary">
            <Briefcase className="w-3.5 h-3.5 mr-1" /> Business & Product Case Studio
          </Badge>
          <h1 className="text-xl md:text-2xl font-black text-text-main tracking-tight">
            Case Study & Product Strategy Rounds
          </h1>
          <p className="text-xs text-text-mute mt-2 leading-relaxed">
            Practice structured problem-solving, product design, metric diagnostics, and market estimations required for Senior PM, Tech Lead, and Strategy roles.
          </p>
        </div>
        <Button
          onClick={() => onStartConfig({ type: 'Product Management', company: 'Google', difficulty: 'Advanced', category: 'Problem Solving' })}
          className="text-xs font-black h-10 px-5 flex items-center gap-2 bg-primary text-black cursor-pointer shrink-0"
        >
          <Play className="w-3.5 h-3.5 fill-black" /> Launch Case Study Mock
        </Button>
      </div>

      {/* Case Scenarios Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {caseScenarios.map((cs, idx) => (
          <Card key={idx} className="bg-[var(--surface)] border-[var(--border)] flex flex-col justify-between hover:border-primary/40 transition-all">
            <CardHeader className="pb-2">
              <div className="flex items-center justify-between">
                <Badge variant="outline" className="text-[10px] font-bold">
                  {cs.company}
                </Badge>
                <Badge variant="primary" className="text-[10px] font-bold">
                  {cs.category}
                </Badge>
              </div>
              <CardTitle className="text-sm font-black text-text-main mt-2">
                {cs.title}
              </CardTitle>
            </CardHeader>
            <CardContent className="flex flex-col justify-between gap-4 h-full">
              <p className="text-xs text-text-mute leading-relaxed">{cs.desc}</p>
              <Button
                onClick={() => onStartConfig({ type: 'Product Management', company: cs.company, difficulty: 'Advanced', category: cs.category })}
                className="text-xs font-black h-9 px-4 bg-primary text-black w-full justify-center"
              >
                Solve Case Scenario <ArrowRight className="w-3.5 h-3.5 ml-1" />
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

    </div>
  );
};
